### ISSUE TITLE
openfga ignores using of external secret

### ISSUE THREAD

**Issue by vaceslav** [openobserve/openobserve-helm-chart#135]
I have an external PostgreSQL server that I want to use. 
So I disable bundled instance

```yaml
postgres:
    enabled: false # disable bundled PostgreSQL
```
I use ArgoCD and I don't want to commit any secrets inside my values.yaml file. So I activated external secret
```yaml
externalSecret:
    enabled: true
    # name of the external secret
    name: "openobserve-secrets"
```

Everything works fine except openfga. 
Openfga is not able to connect to database

```
Error: failed to initialize database connection: failed to connect to `user=userid database=dbname`:
    hostname resolving error: lookup host on 10.43.0.10:53: no such host
    lookup host on 10.43.0.10:53: no such host
Usage:
    openfga migrate [flags]
```

looks like openfga ignores using external secret. 
After defining auth block in values.yaml, openfga starts without problem
```yaml
auth:
    ZO_META_POSTGRES_DSN: "postgres://username:pass@openobserve-pg-cluster-rw:5432/openobserve"
```

But this is a security issue!!!

**Comment by prabhatsharma** [comment]
Fixed

https://github.com/openobserve/openobserve-helm-chart/commit/91e7e559f4b41a5391e86cc27dee7a992f57d0b0

**Comment by vaceslav** [comment]
I updated to helm version `0.14.60`, but the problem still persist.

**Comment by vaceslav** [comment]
@prabhatsharma

**Comment by prabhatsharma** [comment]
try `0.14.61` .
Define DB env in secret using: `OPENFGA_DATASTORE_URI`

**Comment by vaceslav** [comment]
@prabhatsharma Still not working. 

You changed it only for migrate container.
I think we need it also for main conteainer too

https://github.com/openobserve/openobserve-helm-chart/blob/b2ef823c5cc447a6ff4a031c13067f858948c4d2/charts/openobserve/templates/openfga-deployment.yaml#L50

**Comment by vaceslav** [comment]
@prabhatsharma 
This issue is still not fixed. 
the container openfga-migrate still do not use secret
